/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mU_Kernel */

#ifndef _Included_mU_Kernel
#define _Included_mU_Kernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mU_Kernel
 * Method:    _constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mU_Kernel__1constructor
  (JNIEnv *, jclass);

/*
 * Class:     mU_Kernel
 * Method:    _destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mU_Kernel__1destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mU_Kernel
 * Method:    _eval
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_mU_Kernel__1eval
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
