#pragma once

#include "objects/interface.h"
#include "objects/list.h"
#include "objects/pair.h"
#include "objects/chain.h"
#include "objects/tree.h"
#include "objects/dictionary.h"

#include "objects/integer.h"
#include "objects/rational.h"
#include "objects/real.h"
#include "objects/string.h"
#include "objects/symbol.h"
#include "objects/expression.h"
#include "objects/complex.h"
#include "objects/fraction.h"
#include "objects/polynomial.h"
#include "objects/monomial.h"
#include "objects/matrix.h"
